export const mockBooks = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Classic Fiction",
        condition: "Good",
        cover_image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        owner_name: "Maria Popescu",
        owner_image: "https://i.pravatar.cc/150?img=1",
        availableForSwap: true,
        featured: false,
        rating: 4.5,
        publishYear: 1925,
    },
    {
        id: 2,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic Fiction",
        condition: "Like New",
        cover_image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        owner_name: "Ion Ionescu",
        owner_image: "https://i.pravatar.cc/150?img=2",
        availableForSwap: true,
        featured: true,
        rating: 4.8,
        publishYear: 1960,
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        genre: "Dystopian",
        condition: "Good",
        cover_image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        owner_name: "Ana Georgescu",
        owner_image: "https://i.pravatar.cc/150?img=3",
        availableForSwap: true,
        featured: false,
        rating: 4.7,
        publishYear: 1949,
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Romance",
        condition: "New",
        cover_image: "https://covers.openlibrary.org/b/id/8235657-L.jpg",
        owner_name: "Maria Popescu",
        owner_image: "https://i.pravatar.cc/150?img=1",
        availableForSwap: true,
        featured: false,
        rating: 4.6,
        publishYear: 1813,
    },
    {
        id: 5,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        condition: "Like New",
        cover_image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
        owner_name: "Ion Ionescu",
        owner_image: "https://i.pravatar.cc/150?img=2",
        availableForSwap: true,
        featured: true,
        rating: 4.9,
        publishYear: 1937,
    },
    {
        id: 6,
        title: "Harry Potter and the Philosopher's Stone",
        author: "J.K. Rowling",
        genre: "Fantasy",
        condition: "New",
        cover_image: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
        owner_name: "Maria Popescu",
        owner_image: "https://i.pravatar.cc/150?img=1",
        availableForSwap: true,
        featured: false,
        rating: 4.8,
        publishYear: 1997,
    },
    {
        id: 7,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        genre: "Coming of Age",
        condition: "Good",
        cover_image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        owner_name: "Mihai Dumitrescu",
        owner_image: "https://i.pravatar.cc/150?img=4",
        availableForSwap: true,
        featured: false,
        rating: 4.3,
        publishYear: 1951,
    },
    {
        id: 8,
        title: "Brave New World",
        author: "Aldous Huxley",
        genre: "Dystopian",
        condition: "Good",
        cover_image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        owner_name: "Elena Vasilescu",
        owner_image: "https://i.pravatar.cc/150?img=5",
        availableForSwap: true,
        featured: false,
        rating: 4.4,
        publishYear: 1932,
    },
    {
        id: 9,
        title: "The Alchemist",
        author: "Paulo Coelho",
        genre: "Philosophical",
        condition: "Like New",
        cover_image: "https://covers.openlibrary.org/b/id/8235657-L.jpg",
        owner_name: "Mihai Dumitrescu",
        owner_image: "https://i.pravatar.cc/150?img=4",
        availableForSwap: true,
        featured: false,
        rating: 4.5,
        publishYear: 1988,
    },
    {
        id: 10,
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        genre: "Psychological",
        condition: "Good",
        cover_image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        owner_name: "Elena Vasilescu",
        owner_image: "https://i.pravatar.cc/150?img=5",
        availableForSwap: true,
        featured: false,
        rating: 4.7,
        publishYear: 1866,
    },
    {
        id: 11,
        title: "The Book Thief",
        author: "Markus Zusak",
        genre: "Historical",
        condition: "Like New",
        cover_image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
        owner_name: "Ion Ionescu",
        owner_image: "https://i.pravatar.cc/150?img=2",
        availableForSwap: true,
        featured: false,
        rating: 4.6,
        publishYear: 2005,
    },
    {
        id: 12,
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        condition: "Fair",
        cover_image: "https://covers.openlibrary.org/b/id/9255566-L.jpg",
        owner_name: "Ana Georgescu",
        owner_image: "https://i.pravatar.cc/150?img=3",
        availableForSwap: false,
        featured: true,
        rating: 4.9,
        publishYear: 1954,
    },
];
